jQuery(document).ready(function($){
	
	/*//////////////////// REGISTER PAGE ////////////////////////*/
	
	var companies = {
		"Company Name": "",
		"3I Group Plc": "Private Equity",
		"3I Infrastructure Plc": "Speciality & Other Finance",
		"888 Holdings Plc": "Leisure & Hotels",
		"Aa Plc": "Business Services",
		"Aberdeen Asset Management Plc": "Speciality & Other Finance",
		"Aberforth Smaller Companies Trust Plc": "Investment Companies",
		"Acacia Mining Plc": "Mining",
		"Admiral Group Plc": "Insurance",
		"Aggreko Plc": "Business Services",
		"Aldermore Group Plc": "Banks",
		"Alfa Financial Software Holdings Plc": "Technology",
		"Alliance Trust Plc": "Investment Companies",
//		"Allied Minds Plc": "Speciality & Other Finance",
		"Amec Foster Wheeler Plc": "Construction & Building Materials",
		"Anglo American Plc": "Mining",
		"Antofagasta Plc": "Mining",
//		"Ao World Plc": "General Retailers",
		"Ascential Plc": "Media & Entertainment",
		"Ashmore Group Plc": "Speciality & Other Finance",
		"Ashtead Group Plc": "Business Services",
		"Associated British Foods Plc": "Food Producers & Processors",
		"Assura Plc": "Real Estate",
		"Astrazeneca Plc": "Pharmaceuticals and Biotechnology",
		"Auto Trader Group Plc": "Media & Entertainment",
		"Aveva Group Plc": "Software & Computer Services",
		"Aviva Plc": "Life Assurance",
		"B&M European Value Retails Sa": "General Retailers",
		"Bakkavor Group Plc": "Consumer Defensive",
		"Babcock International Group Plc": "Business Services",
		"Bae Systems Plc": "Aerospace & Defence",
		"Balfour Beatty Plc": "Construction & Building Materials",
		"Bankers Investment Trust Plc": "Investment Companies",
		"Barclays Plc": "Banks",
		"Barr": "Beverages",
		"Barratt Developments Plc": "Construction & Building Materials",
		"Bba Aviation Plc": "Transport",
		"BCA Marketplace": "Banks",
		"Beazley Plc": "Insurance",
		"Bellway Plc": "Construction & Building Materials",
		"Berendsen Plc": "Business Services",
		"Berkeley Group Holdings Plc": "Construction & Building Materials",
//		"Bgeo Group Plc": "Banks",
		"Bank of Georgia Group Plc": "Banks",
//		"Bh Macro Ltd": "Investment Companies",
		"Bhp Billiton Plc": "Mining",
		"Big Yellow Group Plc": "Real Estate",
		"Bodycote Plc": "Engineering & Machinery",
		"Booker Group Plc": "Food Producers & Processors",
		"Bovis Homes Group Plc": "Construction & Building Materials",
		"Bp Plc": "Oil & Gas",
		"Brewin Dolphin Holdings Plc": "Speciality & Other Finance",
		"British American Tobacco Plc": "Tobacco",
		"British Empire Trust Plc": "Investment Companies",
		"British Land Co Plc": "Real Estate",
		"Britvic Plc": "Beverages",
		"Brown (N) Group Plc": "General Retailer",
		"Bt Group Plc": "Telecommunication Services",
		"Btg Plc": "Pharmaceuticals and Biotechnology",
		"Bunzl Plc": "Business Services",
		"Burberry Group Plc": "General Retailers",
		"Cairn Energy Plc": "Oil & Gas",
		"Caledonia Investments Plc": "Investment Companies",
		"Capita Plc": "Business Services",
		"Capital & Counties Properties Plc": "Real Estate",
		"Card Factory Plc": "General Retailers",
		"Carillion Plc": "Construction & Building Materials",
		"Carnival Corp": "Leisure & Hotels",
		"Carnival Plc": "Leisure & Hotels",
		"Centamin Plc": "Mining",
		"Centrica Plc": "Utilities - Other",
		"Charter Court": "Financial Servcies",
		"Cineworld Group Plc": "Leisure & Hotels",
		"City Of London Investment Trust Plc": "Investment Companies",
		"Clarkson Plc": "Transport",
		"Close Brothers Group Plc": "Speciality & Other Finance",
		"Cls Hldgs Plc": "Real Estate",
		"Coats Group": "Clothing, Leisure and Personal Products",
		"Cobham Plc": "Aerospace & Defence",
		"Coca-Cola Hbc Ag": "Beverages",
		"Compass Group Plc": "Leisure & Hotels",
		"Computacenter Plc": "Software & Computer Services",
		"Convatec Group Plc": "Health",
		"ContourGlobal Plc": "Utilities",
		"Countryside Properties Plc": "Construction & Building Materials",
		"Cranswick Plc": "Food Producers & Processors",
		"Crest Nicholson Holdings Plc": "Construction & Building Materials",
		"Crh Plc": "Construction & Building Materials",
		"Croda International Plc": "Chemicals",
		"Cybg Plc": "Banks",
		"Daejan Holdings Plc": "Real Estate",
		"Dairy Crest Group Plc": "Food Producers & Processors",
		"Dcc Plc": "Business Services",
//		"Debenhams Plc": "General Retailers",
		"Dechra Pharmaceuticals Plc": "Pharmaceuticals and Biotechnology",
		"Derwent London Plc": "Real Estate",
		"Diageo Plc": "Beverages",
		"Dignity Plc": "Consumer Services",
		"Diploma Plc": "Diversified Industrials",
		"Direct Line Insurance Group Plc": "Insurance",
		"Dixons Carphone Plc": "Telecommunication Services",
		"Domino'S Pizza Group Plc": "Leisure & Hotels",
		"Drax Group Plc": "Electricity",
		"Ds Smith Plc": "Containers & Packaging",
		"Dunelm Group Plc": "General Retailers",
		"Easyjet Plc": "Leisure & Hotels",
		"Edinburgh Dragon": "Equity Investment Instruments",
		"Edinburgh Investment Trust Plc": "Investment Companies",
		"Electra Private Equity Plc": "Investment Companies",
		"Electrocomponents Plc": "Business Services",
		"Elementis Plc": "Chemicals",
		"Entertainment One Ltd": "Media & Entertainment",
		"Essentra Plc": "Business Services",
		"Esure Group Plc": "Insurance",
		"Euromoney Institutional Investor Plc": "Media & Entertainment",
		"Equiniti Group": "Business Support Services",
		"Evraz Plc": "Steel & Other Metals",
		"Experian Plc": "Business Services",
		"F&C Commercial Property Trust Ltd ": "Real Estate",
		"F&C Global Smaller Companies": "Equity Investment Instruments",
		"FDM Group Holdings": "Software & Computer Services",
		"Ferguson Plc": "Support Services",
		"Ferrexpo Plc": "Steel & Other Metals",
		"Fidelity China Special Situations Plc": "Investment Companies",
		"Fidelity European Values Plc": "Investment Companies",
		"Fidessa Group Plc": "Software & Computer Services",
		"Finsbury Growth & Income Trust Plc": "Investment Companies",
		"Firstgroup Plc": "Transport",
		"Fisher (James) & Sons": "Transport",
		"Foreign & Colonial Investment Trust Plc": "Investment Companies",
		"Fresnillo Plc": "Mining",
		"G4S Plc": "Business Services",
		"Galliford Try Plc": "Construction & Building Materials",
		"Games Workshop": "Leisure Goods",
		"Gcp Infrastructure Investments Ltd": "Investment Companies",
		"Genesis Emerging Markets Fund Ltd": "Investment Companies",
		"Genus Plc": "Pharmaceuticals and Biotechnology",
		"Gkn Plc": "Automobiles & Parts",
		"Glaxosmithkline Plc": "Pharmaceuticals and Biotechnology",
		"Glencore Plc": "Mining",
		"Go-Ahead Group Plc": "Transport",
		"Grafton Group Plc": "Construction & Building Materials",
		"Grainger Plc": "Real Estate",
		"Great Portland Estates Plc": "Real Estate",
		"Greencoat Uk Wind Plc": "Investment Companies",
		"Greencore Group Plc": "Food Producers & Processors",
		"Greene King Plc": "Leisure & Hotels",
		"Greggs Plc": "Food & Drug Retailers",
		"Gvc Holdings Plc": "Leisure & Hotels",
		"Halfords Group Plc": "General Retailers",
		"Halma Plc": "Engineering & Machinery",
		"Hammerson Plc": "Real Estate",
		"Hansteen Hldgs Plc": "Real Estate",
		"Harbourvest Global Private Equity Ltd": "Investment Companies",
		"Hargreaves Lansdown Plc": "Speciality & Other Finance",
		"Hastings Group Holdings Plc": "Insurance",
		"Hays Plc": "Business Services",
		"Herald Investment": "Equity Investment Instruments",
		"Hicl Infrastructure Co Ltd ": "Investment Companies",
		"Hikma Pharmaceuticals Plc": "Pharmaceuticals and Biotechnology",
		"Hill & Smith Hldgs Plc": "Engineering & Machinery",
		"Hiscox Ltd": "Insurance",
		"Hochschild Mining Plc": "Mining",
		"Homeserve Plc": "Business Services",
		"Howden Joinery Group Plc": "General Retailers",
		"Hsbc Holdings Plc": "Banks",
		"Hunting Plc": "Oil & Gas",
		"Ibstock Plc": "Construction & Building Materials",
		"Ig Group Holdings Plc": "Speciality & Other Finance",
		"Imi Plc": "Engineering & Machinery",
		"Imperial Brands Plc": "Tobacco",
		"Inchcape Plc": "Automobiles & Parts",
		"Indivior Plc": "Pharmaceuticals and Biotechnology",
		"Informa Plc": "Media & Entertainment",
		"Inmarsat Plc": "Telecommunication Services",
		"Intercontinental Hotels Group Plc": "Leisure & Hotels",
		"Intermediate Capital Group Plc": "Speciality & Other Finance",
		"International Consolidated Airlines Group Sa ": "Leisure & Hotels",
		"International Public Partnerships Ltd ": "Investment Companies",
		"Intertek Group Plc": "Business Services",
		"Intu Properties Plc": "Real Estate",
		"Investec Plc": "Speciality & Other Finance",
		"Ip Group Plc": "Speciality & Other Finance",
		"Itv Plc": "Media & Entertainment",
		"Iwg Plc": "Business Services",
		"Janus Henderson Group Plc": "Speciality & Other Finance",
		"Jardine Lloyd Thompson Group Plc": "Insurance",
		"Jd Sports Fashion Plc": "General Retailers",
		"John Laing Group Plc": "Speciality & Other Finance",
		"John Laing Infrastructure Fund Ltd": "Investment Companies",
		"John Wood Group": "Oil Equipment & Services",
		"Johnson Matthey Plc": "Chemicals",
		"Jpmorgan American Investment Trust Plc": "Investment Companies",
		"Jpmorgan Emerging Markets Investment Trust Plc": "Investment Companies",
		"Jpmorgan Indian Investment Trust Plc": "Investment Companies",
		"Jupiter Fund Management Plc": "Speciality & Other Finance",
		"Just Eat Plc": "Consumer Services",
		"Just Group Plc": "Speciality & Other Finance",
		"Kaz Minerals Plc": "Steel & Other Metals",
//		"Keller Group Plc": "Construction & Building Materials",
		"Kennedy Wilson Europe Real Estate Plc": "Investment Companies",
		"Kier Group Plc": "Construction & Building Materials",
		"Kingfisher Plc": "General Retailers",
		"Ladbrokes Coral Group Plc": "Leisure & Hotels",
		"Lancashire Holdings Ltd": "Insurance",
		"Land Securities Group Plc": "Real Estate",
		"Legal & General Group Plc": "Life Assurance",
		"Lloyds Banking Group Plc": "Banks",
		"London Stock Exchange Group Plc": "Speciality & Other Finance",
		"Londonmetric Property Plc": "Real Estate",
		"Man Group Plc": "Speciality & Other Finance",
		"Marks & Spencer Group Plc": "General Retailers",
		"Marshalls Plc": "Construction & Building Materials",
		"Marston'S Plc": "Leisure & Hotels",
		"Mccarthy & Stone Plc": "Construction & Building Materials",
		"Mediclinic International Plc": "Health",
		"Meggitt Plc": "Aerospace & Defence",
		"Melrose Industries": "Engineering & Machinery",
		"Mercantile Investment Trust Plc": "Investment Companies",
		"Merlin Entertainments Plc": "Leisure & Hotels",
		"Metro Bank Plc": "Banks",
		"Micro Focus International Plc": "Software & Computer Services",
		"Millennium & Copthorne Hotels Plc": "Leisure & Hotels",
		"Mitchells & Butlers Plc": "Leisure & Hotels",
		"Mitie Group Plc": "Business Services",
		"Mondi Plc": "Forestry & Paper",
		"Moneysupermarket.Com Group Plc": "Media & Entertainment",
		"Monks Investment Trust Plc": "Investment Companies",
		"Morgan Advanced Materials Plc": "Engineering & Machinery",
		"Murray International Trust Plc": "Investment Companies",
		"National Express Group Plc": "Transport",
		"National Grid Plc": "Electricity",
		"Nb Global Floating Rate Income Fund Ltd": "Investment Companies",
		"Newriver Reit Plc": "Real Estate",
		"Nex Group Plc": "Speciality & Other Finance",
		"Next Plc": "General Retailers",
		"Nmc Health Plc": "Health",
//		"Northgate Plc": "Transport",
		"Nostrum Oil & Gas Plc": "Oil & Gas",
		"Ocado Group Plc": "Food & Drug Retailers",
		"Old Mutual Plc": "Life Assurance",
		"On the Beach": "Travel & Leisure",
		"Onesavings Bank Plc": "Banks",
		"P2P Global Investments Plc": "Investment Companies",
		"Paddy Power Betfair Plc": "Leisure & Hotels",
		"Pagegroup Plc": "Business Services",
		"Pantheon International": "Equity Investment Instruments",
		"Paragon Banking Group Plc": "Speciality & Other Finance",
		"Paypoint Plc": "Business Services",
		"Paysafe Group Plc": "Speciality & Other Finance",
		"Pearson Plc": "Media & Entertainment",
		"Pennon Group Plc": "Utilities - Other",
		"Perpetual Income & Growth Investment Trust Plc": "Investment Companies",
		"Pershing Square Holdings": "Investment Companies",
		"Persimmon Plc": "Construction & Building Materials",
		"Personal Assets Trust Plc": "Investment Companies",
		"Petra Diamonds Limited": "Mining",
		"Petrofac Ltd": "Oil & Gas",
		"Pets At Home Group Plc": "General Retailers",
		"Phoenix Group Holdings ": "Speciality & Other Finance",
		"Playtech Plc": "Software & Computer Services",
		"Polar Capital Technology Trust Plc": "Investment Companies",
		"Polymetal International Plc": "Mining",
		"Polypipe Group Plc": "Construction & Building Materials",
		"Primary Health Trusts": "Real Estate",
		"Provident Financial Plc": "Speciality & Other Finance",
		"Prudential Plc": "Life Assurance",
		"PureCircle Ltd": "Food Producers",
		"Pz Cussons Plc": "Clothing, Leisure and Personal Products",
		"Qinetiq Group Plc": "Aerospace & Defence",
		"Quilter Plc": "Life Assurance",
		"Randgold Resources Ltd": "Mining",
		"Rank Group Plc": "Leisure & Hotels",
		"Rathbone Brothers Plc": "Speciality & Other Finance",
		"RDI Reit": "Real Estate",
		"Reckitt Benckiser Group Plc": "Clothing, Leisure and Personal Products",
		"Redefine International Plc": "Real Estate",
		"Redrow Plc": "Construction & Building Materials",
		"Relx Plc": "Media & Entertainment",
		"Renewables Infrastructure Group Ltd": "Investment Companies",
		"Renewi Plc": "Support Services",
		"Renishaw Plc": "Electronic & Electrical Equipment",
		"Rentokil Initial Plc": "Business Services",
		"Restaurant Group Plc": "Leisure & Hotels",
		"RHI Magnesita": "Industrial Engineering",
		"Rightmove Plc": "Media & Entertainment",
		"Rio Tinto Plc": "Mining",
		"Rit Capital Partners Plc": "Investment Companies",
		"Riverstone Energy Ltd": "Investment Companies",
		"Rolls-Royce Holdings Plc": "Aerospace & Defence",
		"Rotork Plc": "Engineering & Machinery",
		"Royal Bank Of Scotland Group Plc": "Banks",
		"Royal Dutch Shell Plc": "Oil & Gas",
		"Royal Mail Plc": "Transport",
		"Rpc Group Plc": "Containers & Packaging",
		"Rsa Insurance Group Plc": "Insurance",
		"Safestore Holdings Plc": "Real Estate",
		"Saga Plc": "Insurance",
		"Sage Group Plc": "Software & Computer Services",
		"Sainsbury’s Supermarkets Ltd": "Food & Drug Retailers",
		"Sanne Group Plc": "Financial Services",
		"Savills Plc": "Real Estate",
		"Schroder Asia PA": "Equity Investment Instruments",
		"Schroders Plc": "Speciality & Other Finance",
		"Scottish Investment Trust Plc": "Investment Companies",
		"Scottish Mortgage Investment Trust Plc": "Investment Companies",
		"Segro Plc": "Real Estate",
		"Senior Plc": "Aerospace & Defence",
		"Serco Group Plc": "Business Services",
		"Severn Trent Plc": "Utilities - Other",
		"Shaftesbury Plc": "Real Estate",
		"Shawbrook Group Plc": "Speciality & Other Finance",
		"Shire Plc": "Pharmaceuticals and Biotechnology",
		"Sig Plc": "Construction & Building Materials",
		"Sirius Minerals": "Mining",
		"Sky Plc": "Media & Entertainment",
		"Smith & Nephew Plc": "Health",
		"Smiths Group Plc": "Engineering & Machinery",
		"Smurfit Kappa Group Plc": "Containers & Packaging",
		"Softcat Plc": "Software & Computer Services",
		"Sophos Group Plc": "Software & Computer Services",
		"Spectris Plc": "Electronic & Electrical Equipment",
		"Spirax-Sarco Engineering Plc": "Engineering & Machinery",
		"Spire Healthcare Group Plc": "Health",
		"Sports Direct International Plc": "General Retailers",
		"Sse Plc": "Electricity",
		"Ssp Group Plc": "Food Producers & Processors",
		"St James'S Place Plc": "Life Assurance",
		"St Modwen Properties Plc": "Real Estate",
		"Stagecoach Group Plc": "Transport",
		"Standard Chartered Plc": "Banks",
//		"Standard Life Plc": "Life Assurance",
		"Standard Life Aberdeen": "Life Assurance",
		"Stobart Group": "Real Estate",
		"Superdry": "Clothing & Accessories",
		"Supergroup Plc": "Clothing, Leisure and Personal Products",
//		"Svg Capital Plc": "Investment Companies",
		"Syncona Ltd ": "Investment Companies",
		"Synthomer Plc": "Chemicals",
		"Talktalk Telecom Group Plc": "Telecommunication Services",
		"Tate & Lyle Plc": "Food Producers & Processors",
		"Taylor Wimpey Plc": "Construction & Building Materials",
		"TBC Bank Group Plc": "Banks",
		"Ted Baker Plc": "General Retailers",
		"Telecom Plus Plc": "Telecommunication Services",
		"Temple Bar Investment Trust Plc": "Investment Companies",
		"Templeton Emerging Markets Investment Trust Plc": "Investment Companies",
		"Tesco Plc": "Food & Drug Retailers",
		"Thomas Cook Group Plc": "Leisure & Hotels",
		"TI Fluid Systems": "Automobiles & Parts",
		"Tp Icap Plc": "Speciality & Other Finance",
		"Tr Property Investment Trust Plc": "Real Estate",
		"Travis Perkins Plc": "Construction & Building Materials",
		"Tritax Big Box Reit Plc": "Real Estate",
		"Tui Ag ": "Leisure & Hotels",
		"Tullow Oil Plc": "Oil & Gas",
		"Ubm Plc": "Media & Entertainment",
		"Udg Healthcare Plc": "Health",
		"Uk Commercial Property Trust Ltd": "Real Estate",
		"Ultra Electronics Hldgs Plc": "Aerospace & Defence",
		"Unilever Plc": "Food Producers & Processors",
		"Unite Group Plc": "Real Estate",
		"United Utilities Group Plc": "Utilities - Other",
		"Vectura Group Plc": "Pharmaceuticals and Biotechnology",
		"Vedanta Resources Plc": "Mining",
		"Vesuvius Plc": "Engineering & Machinery",
		"Victrex Plc": "Chemicals",
		"Vinacapital Vietnam Opportunity": "Equity Investment Instruments",
		"Virgin Money Holdings ": "Speciality & Other Finance",
		"Vodafone Group Plc": "Telecommunication Services",
		"Weir Group Plc": "Engineering & Machinery",
		"Wetherspoon": "Leisure & Hotels",
		"Wh Smith Plc": "General Retailers",
		"Whitbread Plc": "Leisure & Hotels",
		"William Hill Plc": "Leisure & Hotels",
		"Witan Investment Trust Plc": "Investment Companies",
		"Wizz Air Holdings Plc": "Leisure & Hotels",
		"Wm Morrison Supermarkets Plc": "Food & Drug Retailers",
		"Wolseley Plc": "Construction & Building Materials",
		"Wood Group ": "Oil & Gas",
		"Woodford Patient Capital Trust Plc": "Investment Companies",
		"Workspace Group Plc": "Real Estate",
		"Worldpay Group Plc": "Business Services",
		"Worldwide Healthcare Trust Plc": "Investment Companies",
		"Wpp Plc": "Media & Entertainment",
//		"Ws Atkins Plc": "Business Services",
		"Zpg Plc": "Media & Entertainment",
	};
	
	var company_name = Object.keys(companies);
	
	
	var ftseIndex = {
		'100': [
			"G4S Plc",
			"Segro Plc",
			"3I Group Plc",
			"Admiral Group Plc",
			"Anglo American Plc",
			"Antofagasta Plc",
			"Ashtead Group Plc",
			"Associated British Foods Plc",
			"Astrazeneca Plc",
			"Aviva Plc",
			"Babcock International Group Plc",
			"Bae Systems Plc",
			"Barclays Plc",
			"Barratt Developments Plc",
			"Berkeley Group Holdings Plc",
			"Bhp Billiton Plc",
			"Bp Plc",
			"British American Tobacco Plc",
			"British Land Co Plc",
			"Bt Group Plc",
			"Bunzl Plc",
			"Burberry Group Plc",
			"Carnival Corp",
			"Carnival Plc",
			"Centrica Plc",
			"Coca-Cola Hbc Ag",
			"Compass Group Plc",
			"Convatec Group Plc",
			"Crh Plc",
			"Croda International Plc",
			"Dcc Plc",
			"Diageo Plc",
			"Direct Line Insurance Group Plc",
			"Ds Smith Plc",
			"Easyjet Plc",
			"Experian Plc",
			"Ferguson Plc",
			"Fresnillo Plc",
			"Gkn Plc",
			"Glaxosmithkline Plc",
			"Glencore Plc",
			"Hammerson Plc",
			"Hargreaves Lansdown Plc",
			"Hsbc Holdings Plc",
			"Imperial Brands Plc",
			"Informa Plc",
			"Intercontinental Hotels Group Plc",
			"International Consolidated Airlines Group Sa ",
			"Intertek Group Plc",
			"Itv Plc",
			"Johnson Matthey Plc",
			"Kingfisher Plc",
			"Land Securities Group Plc",
			"Legal & General Group Plc",
			"Lloyds Banking Group Plc",
			"London Stock Exchange Group Plc",
			"Marks & Spencer Group Plc",
			"Mediclinic International Plc",
			"Merlin Entertainments Plc",
			"Micro Focus International Plc",
			"Mondi Plc",
			"National Grid Plc",
			"Next Plc",
			"Old Mutual Plc",
			"Paddy Power Betfair Plc",
			"Pearson Plc",
			"Persimmon Plc",
			"Provident Financial Plc",
			"Prudential Plc",
			"Quilter Plc",
			"Randgold Resources Ltd",
			"Reckitt Benckiser Group Plc",
			"Relx Plc",
			"Rentokil Initial Plc",
			"Rio Tinto Plc",
			"Rolls-Royce Holdings Plc",
			"Royal Bank Of Scotland Group Plc",
			"Royal Dutch Shell Plc",
			"Royal Mail Plc",
			"Rsa Insurance Group Plc",
			"Sage Group Plc",
			"Sainsbury’s Supermarkets Ltd",
			"Schroders Plc",
			"Scottish Mortgage Investment Trust Plc",
			"Severn Trent Plc",
			"Shire Plc",
			"Sky Plc",
			"Smith & Nephew Plc",
			"Smiths Group Plc",
			"Smurfit Kappa Group Plc",
			"Sse Plc",
			"St James'S Place Plc",
			"Standard Chartered Plc",
			"Standard Life Plc",
			"Standard Life Aberdeen",
			"Taylor Wimpey Plc",
			"Tesco Plc",
			"Tui Ag ",
			"Unilever Plc",
			"United Utilities Group Plc",
			"Vodafone Group Plc",
			"Whitbread Plc",
			"Wm Morrison Supermarkets Plc",
			"Wolseley Plc",
			"Worldpay Group Plc",
			"Wpp Plc"
		],
		'250': [
			"Alfa Financial Software Holdings Plc",
			"888 Holdings Plc",
			"Vinacapital Vietnam Opportunity",
			"B&M European Value Retails SA",
			"Bakkavor Group Plc",
			"BCA Marketplace",
			"Charter Court",
			"ContourGlobal Plc",
			"Edinburgh Dragon",
			"Equiniti Group",
			"Games Workshop",
			"On the Beach",
			"TBC Bank Group Plc",
			"Pantheon International",
			"Primary Health Trusts",
			"PureCircle Ltd",
			"RDI Reit",
			"Renewi Plc",
			"Coats Group",
			"FDM Group Holdings",
			"Melrose Industries",
			"Pershing Square Holdings",
			"Sirius Minerals",
			"Hikma Pharmaceuticals Plc",
			"Superdry",
			"RHI Magnesita",
			"Intu Properties Plc",
			"Schroder Asia PA",
			"3I Infrastructure Plc",
			"Aa Plc",
			"Aberdeen Asset Management Plc",
			"Aberforth Smaller Companies Trust Plc",
			"Acacia Mining Plc",
			"Aggreko Plc",
			"Aldermore Group Plc",
			"Alliance Trust Plc",
			"Allied Minds Plc",
			"Amec Foster Wheeler Plc",
			"Ao World Plc",
			"Ascential Plc",
			"Ashmore Group Plc",
			"Assura Plc",
			"Auto Trader Group Plc",
			"Aveva Group Plc",
			"John Wood Group",
			"B&M European Value Retail Sa",
			"Balfour Beatty Plc",
			"Bankers Investment Trust Plc",
			"Barr",
			"Bba Aviation Plc",
			"Beazley Plc",
			"Bellway Plc",
			"Berendsen Plc",
			"Bgeo Group Plc",
			"Bank of Georgia Group Plc",
			"Bh Macro Ltd",
			"Big Yellow Group Plc",
			"Bodycote Plc",
			"Booker Group Plc",
			"Bovis Homes Group Plc",
			"Brewin Dolphin Holdings Plc",
			"British Empire Trust Plc",
			"Britvic Plc",
			"Brown (N) Group Plc",
			"Btg Plc",
			"Cairn Energy Plc",
			"Caledonia Investments Plc",
			"Capita Plc",
			"Capital & Counties Properties Plc",
			"Card Factory Plc",
			"Carillion Plc",
			"Centamin Plc",
			"Cineworld Group Plc",
			"City Of London Investment Trust Plc",
			"Clarkson Plc",
			"Close Brothers Group Plc",
			"Cls Hldgs Plc",
			"Cobham Plc",
			"Computacenter Plc",
			"Countryside Properties Plc",
			"Cranswick Plc",
			"Crest Nicholson Holdings Plc",
			"Cybg Plc",
			"Daejan Holdings Plc",
			"Dairy Crest Group Plc",
			"Debenhams Plc",
			"Dechra Pharmaceuticals Plc",
			"Derwent London Plc",
			"Dignity Plc",
			"Diploma Plc",
			"Dixons Carphone Plc",
			"Domino'S Pizza Group Plc",
			"Drax Group Plc",
			"Dunelm Group Plc",
			"Edinburgh Investment Trust Plc",
			"Electra Private Equity Plc",
			"Electrocomponents Plc",
			"Elementis Plc",
			"Entertainment One Ltd",
			"Essentra Plc",
			"Esure Group Plc",
			"Euromoney Institutional Investor Plc",
			"Evraz Plc",
			"F&C Commercial Property Trust Ltd ",
			"F&C Global Smaller Companies",
			"Ferrexpo Plc",
			"Fidelity China Special Situations Plc",
			"Fidelity European Values Plc",
			"Fidessa Group Plc",
			"Finsbury Growth & Income Trust Plc",
			"Firstgroup Plc",
			"Fisher (James) & Sons",
			"Foreign & Colonial Investment Trust Plc",
			"Galliford Try Plc",
			"Gcp Infrastructure Investments Ltd",
			"Genesis Emerging Markets Fund Ltd",
			"Genus Plc",
			"Go-Ahead Group Plc",
			"Grafton Group Plc",
			"Grainger Plc",
			"Great Portland Estates Plc",
			"Greencoat Uk Wind Plc",
			"Greencore Group Plc",
			"Greene King Plc",
			"Greggs Plc",
			"Gvc Holdings Plc",
			"Halfords Group Plc",
			"Halma Plc",
			"Hansteen Hldgs Plc",
			"Harbourvest Global Private Equity Ltd",
			"Hastings Group Holdings Plc",
			"Hays Plc",
			"Herald Investment",
			"Hicl Infrastructure Co Ltd ",
			"Hill & Smith Hldgs Plc",
			"Hiscox Ltd",
			"Hochschild Mining Plc",
			"Homeserve Plc",
			"Howden Joinery Group Plc",
			"Hunting Plc",
			"Ibstock Plc",
			"Ig Group Holdings Plc",
			"Imi Plc",
			"Inchcape Plc",
			"Indivior Plc",
			"Inmarsat Plc",
			"Intermediate Capital Group Plc",
			"International Public Partnerships Ltd ",
			"Investec Plc",
			"Ip Group Plc",
			"Iwg Plc",
			"Janus Henderson Group Plc",
			"Jardine Lloyd Thompson Group Plc",
			"Jd Sports Fashion Plc",
			"John Laing Group Plc",
			"John Laing Infrastructure Fund Ltd",
			"Jpmorgan American Investment Trust Plc",
			"Jpmorgan Emerging Markets Investment Trust Plc",
			"Jpmorgan Indian Investment Trust Plc",
			"Jupiter Fund Management Plc",
			"Just Eat Plc",
			"Just Group Plc",
			"Kaz Minerals Plc",
			"Keller Group Plc",
			"Kennedy Wilson Europe Real Estate Plc",
			"Kier Group Plc",
			"Ladbrokes Coral Group Plc",
			"Lancashire Holdings Ltd",
			"Londonmetric Property Plc",
			"Man Group Plc",
			"Marshalls Plc",
			"Marston'S Plc",
			"Mccarthy & Stone Plc",
			"Meggitt Plc",
			"Mercantile Investment Trust Plc",
			"Metro Bank Plc",
			"Millennium & Copthorne Hotels Plc",
			"Mitchells & Butlers Plc",
			"Mitie Group Plc",
			"Moneysupermarket.Com Group Plc",
			"Monks Investment Trust Plc",
			"Morgan Advanced Materials Plc",
			"Murray International Trust Plc",
			"National Express Group Plc",
			"Nb Global Floating Rate Income Fund Ltd",
			"Newriver Reit Plc",
			"Nex Group Plc",
			"Nmc Health Plc",
			"Northgate Plc",
			"Nostrum Oil & Gas Plc",
			"Ocado Group Plc",
			"Onesavings Bank Plc",
			"P2P Global Investments Plc",
			"Pagegroup Plc",
			"Paragon Banking Group Plc",
			"Paypoint Plc",
			"Paysafe Group Plc",
			"Pennon Group Plc",
			"Perpetual Income & Growth Investment Trust Plc",
			"Personal Assets Trust Plc",
			"Petra Diamonds Limited",
			"Petrofac Ltd",
			"Pets At Home Group Plc",
			"Phoenix Group Holdings ",
			"Playtech Plc",
			"Polar Capital Technology Trust Plc",
			"Polymetal International Plc",
			"Polypipe Group Plc",
			"Pz Cussons Plc",
			"Qinetiq Group Plc",
			"Rank Group Plc",
			"Rathbone Brothers Plc",
			"Redefine International Plc",
			"Redrow Plc",
			"Renewables Infrastructure Group Ltd",
			"Renishaw Plc",
			"Restaurant Group Plc",
			"Rightmove Plc",
			"Rit Capital Partners Plc",
			"Riverstone Energy Ltd",
			"Rotork Plc",
			"Rpc Group Plc",
			"Safestore Holdings Plc",
			"Saga Plc",
			"Sanne Group Plc",
			"Savills Plc",
			"Scottish Investment Trust Plc",
			"Senior Plc",
			"Serco Group Plc",
			"Shaftesbury Plc",
			"Shawbrook Group Plc",
			"Sig Plc",
			"Softcat Plc",
			"Sophos Group Plc",
			"Spectris Plc",
			"Spirax-Sarco Engineering Plc",
			"Spire Healthcare Group Plc",
			"Sports Direct International Plc",
			"Ssp Group Plc",
			"St Modwen Properties Plc",
			"Stagecoach Group Plc",
			"Stobart Group",
			"Supergroup Plc",
			"Svg Capital Plc",
			"Syncona Ltd ",
			"Synthomer Plc",
			"Talktalk Telecom Group Plc",
			"Tate & Lyle Plc",
			"Ted Baker Plc",
			"Telecom Plus Plc",
			"Temple Bar Investment Trust Plc",
			"Templeton Emerging Markets Investment Trust Plc",
			"Thomas Cook Group Plc",
			"TI Fluid Systems",
			"Tp Icap Plc",
			"Tr Property Investment Trust Plc",
			"Travis Perkins Plc",
			"Tritax Big Box Reit Plc",
			"Tullow Oil Plc",
			"Ubm Plc",
			"Udg Healthcare Plc",
			"Uk Commercial Property Trust Ltd",
			"Ultra Electronics Hldgs Plc",
			"Unite Group Plc",
			"Vectura Group Plc",
			"Vedanta Resources Plc",
			"Vesuvius Plc",
			"Victrex Plc",
			"Virgin Money Holdings ",
			"Weir Group Plc",
			"Wetherspoon",
			"Wh Smith Plc",
			"William Hill Plc",
			"Witan Investment Trust Plc",
			"Wizz Air Holdings Plc",
			"Wood Group ",
			"Woodford Patient Capital Trust Plc",
			"Workspace Group Plc",
			"Worldwide Healthcare Trust Plc",
			"Ws Atkins Plc",
			"Zpg Plc"
		]
	};
	
	var invTrust = [];

	var emptyFields = true;
	var emailCheck = false;
	var passCheck = false;
	var fNameCheck = false;
	var sNameCheck = false;
	var telCheck = false;
	var compCheck = false;

	var errorMessages = {
		company: "Please select company",
		empty: "Please complete all fields",
		emailFormat: "Please make sure you use a valid email address",
		emailMatch: "Your email addresses do not match",
		passwordFormat: "Please make sure your password meets the minimum requirements",
		passwordMatch: "Your passwords do not match",
		disclaimer: "Please tick the box to proceed",
		lettersOnly: "Please use only letters when typing your name",
		numbersOnly: "Please use only numbers when typing your phone number"
	};

	$("#company-name").select2({
		data: company_name
	});

	$("#company-name").on('change', function(){
		var comp = $(this).val();
		$('#sector, #sector_dis').val(companies[comp]);
		
		for(var key in ftseIndex) {
			var obj = ftseIndex[key];
			if(jQuery.inArray(comp, ftseIndex[key]) !== -1) {
				$('#ftseIndex').val(key);
			}
		}
		
		if(jQuery.inArray(comp, invTrust) !== -1) {
			$('#invTrust').val('Yes');
		} else {
			$('#invTrust').val('No');
		}

		if( comp === 'Company Name' || comp === '' ) {
			$(this).siblings('.error_msg').text(errorMessages.company);
			compCheck = false;
		} else {
			$(this).siblings('.error_msg').text('');
			compCheck = true;
		}
	});
	
	$('#disclaimer').on('change', function(){
		if( $('input#disclaimer').is(':checked') ) {
			$(this).siblings('.error_msg').text('');
		} else {
			$(this).siblings('.error_msg').text(errorMessages.disclaimer);
		}
	});

	$('input[type!="hidden"]').on('keyup blur', function(){
		var inputVal = $(this).val();

		if( inputVal.length == 0 ) {
			$(this).addClass('fail');
		} else {
			$(this).removeClass('fail');
			$(this).next('.error_msg').text('');
		}
		
		if( $(this).is('#email') ) {
			if( inputVal.indexOf('@') > -1 && inputVal.indexOf('.') > -1 ) {
				$(this).next('.error_msg').text('');
			} else {
				$(this).next('.error_msg').text(errorMessages.emailFormat);
			}
		}

		if( $(this).is('#email2') ) {
			if( $('#email').val() == inputVal ) {
				$(this).next('.error_msg').text('');
				emailCheck = true;
			} else {
				$(this).next('.error_msg').text(errorMessages.emailMatch);
				emailCheck = false;
			}
		}
		
		if( $(this).is('#first-name') ) {
			function hasNumber(myString) {
			  return /\d/.test(myString);
			}

			if( !hasNumber(inputVal) ) {
				$(this).next('.error_msg').text('');
				fNameCheck = true;
			} else {
				$(this).next('.error_msg').text(errorMessages.lettersOnly);
				fNameCheck = false;
			}
		}
		
		if( $(this).is('#last-name') ) {
			function hasNumber(myString) {
			  return /\d/.test(myString);
			}

			if( !hasNumber(inputVal) ) {
				$(this).next('.error_msg').text('');
				sNameCheck = true;
			} else {
				$(this).next('.error_msg').text(errorMessages.lettersOnly);
				sNameCheck = false;
			}
		}
		
		if( $(this).is('#contact-phone') ) {
			if( /^(?=.*\d)[\d ]+$/.test(inputVal) ) {
				$(this).next('.error_msg').text('');
				telCheck = true;
			} else {
				$(this).next('.error_msg').text(errorMessages.numbersOnly);
				telCheck = false;
			}
		}

		var empty = $('input[type!="hidden"], input:not([disabled])').filter(function() {
			return this.value === "";
		});

		if(empty.length) {
			emptyFields = true;
		} else {
			emptyFields = false;
		}
	});

	$('input, .checkbox').on('blur keyup click', function(){
		if( !emptyFields && compCheck && fNameCheck && sNameCheck && emailCheck && telCheck && $('input#disclaimer').is(':checked') ) {
			$('#submit-button').prop('disabled', false);
			$('.overlay').hide();
		} else {
			$('#submit-button').prop('disabled', true);
			$('.overlay').show();
		}
	});
	
//	$('.checkbox').on('click', function(){
//		if ($('input.checkbox').is(':checked')) {
//			$('.overlay').hide();
//		} else {
//			$('.overlay').show();
//		}
//	});

	$('#company-name').on('change', function(){
		if( compCheck && fNameCheck && sNameCheck && emailCheck && telCheck && $('input#disclaimer').is(':checked') ) {
			$('.overlay').hide();
			$('#submit-button').prop('disabled', false);
		} else {
			$('.overlay').show();
			$('#submit-button').prop('disabled', true);
		}
	});
	
	$('input').addClass('fail');
	
	$('.overlay-two').click(function(){
		$('.fail:not(#disclaimer, #company-name)').siblings('.error_msg').text(errorMessages.empty);
		if( !$('input#disclaimer').is(':checked') ) $('#disclaimer').siblings('.error_msg').text(errorMessages.disclaimer);
		if( $("#company-name").val() == 'Company Name' || $("#company-name").val() == '' ) $('#company-name').siblings('.error_msg').text(errorMessages.company);
	});
	
});